### ISSUE TITLE
How to build an image labeling websit with AIDA?

### ISSUE THREAD

**Issue by wulipc** [alanaberdeen/annotate#1]
Hello, alanaberdeen,

Recently, I have been looking for an image labelling tool and compared a lot of image labelling tools mentioned in Wikipedia webpage.  I found your label tool, AIDI, is outstanding and it suits me very well.
but this project seems to contain only the front-end part, and I wonder how I can deploy this tool on my server.
Any information would be appreciated.
thank you so much. ^_^

wulipc
2018-02-02 20:28:59

**Comment by alanaberdeen** [comment]
Hey, 

Nice to hear people are interested! 

Sure I can try and point you in the right direction. As you say, in the current form AIDA is a 'just' a front-end interface. This was a purposeful design choice. We wanted to keep each part modular and decoupled from each other for ease of development and increased generallity. 

But you could quite easily use it to annotate or label your own images. This would require adjusting the HTTP requests to pull the images from your server and similarly adjusting the save functionality to specify a safe location to store your new annotations. There is a single configuration JSON object that specifies the entire state of the entire application. You may want to save the whole thing or just the bits you care about. 

Feel free to fork this and have a dig around in the code. I'll have a go at helping out further if you get stuck! 


P.S. 
There are tentative plans to enable this kind of thing directly with simple application settings. But it's something I haven't had time to really dig into just yet. Will let you know when things move further along!

**Comment by wulipc** [comment]
It is so kind of you to help me out. I  will dive right in and see how it works.
Thank you.
Sorry for the late reply.

**Comment by mfojtak** [comment]
Is there a simple documentation on how to build and deploy this web app?

**Comment by alanaberdeen** [comment]
Hi Michal, 

The code is bundled together using [Webpack](https://webpack.js.org/). 
Therefore, the working process is something like the following: 

1.  Clone the repo
2.  Install dependencies via `npm install`
3.  For development: start a hot-reloading dev server with `npm run dev`
4.  For deployment: bundle together with `npm run build`

I've made some changes recently so be sure to clone the latest from master - it should be an easier code base to work with!

**Comment by djshu** [comment]
Wow, thank you! I got the demo I want. But how to open an image to annotate? I try to load an image like this, but nothing loaded

![2018-08-02 11-26-38](https://user-images.githubusercontent.com/25275145/43560888-1e90ede6-9647-11e8-9278-bba6bd6e6e63.png)
