### ISSUE TITLE
AIDA freezing browser with zoom + opacity slider

### ISSUE THREAD

**Issue by rcasero** [alanaberdeen/annotate#10]
Hi @alanaberdeen ,

System: Ubuntu Artful.

With AIDA current version 3816c9d, we have seen some interface bugs on a histology image with annotations. Namely, if I open the histology image on localhost with 1 layer of annotations, move the opacity slider below 100%, and zoom in, before reaching the highest zoom level, Chrome will freeze.

Only solution then is to kill the tab that's running AIDA.

We have also seen random non-reproducible bugs on remote browsing from another machine with Chrome and Firefox, where the annotations suddenly disappear when opacity goes below a threshold, or the image zooms in but the annotations don't, or they get a translation offset from their true position.

As long as the opacity slider is not touched, I don't seem to get those problems.

**Comment by alanaberdeen** [comment]
Hi @rcasero, 

Ok, thanks for the heads up - I'll dig into this
