### ISSUE TITLE
Measure tool shows 0um

### ISSUE THREAD

**Issue by rcasero** [alanaberdeen/annotate#16]
I've created a .dzi file from an .ndpi with `vips dzsave foo.ndpi foo`, a fat histology slice. In the navigator, when using the Measure tool, it's giving me 0um for any measure line I draw. Not sure whether this is a known bug, or it's not implemented yet, or it has to do with my particular file, but just to let you know.

**Comment by alanaberdeen** [comment]
HI @rcasero 

Yes, the Measure tool was a brief experiment that I had working in a very limited set of circumstances. It needs some extra effort to make it a bit more robust, that's on the list but not a priority currently. 

Thanks for the heads up
