### ISSUE TITLE
Move Tool freezes interface and Delete Tool cannot delete single objects

### ISSUE THREAD

**Issue by rcasero** [alanaberdeen/annotate#17]
In commit dd989e2, "Move Tool" with ~40,000 annotations, hangs up the interface. Just clicking on it, makes the interface freeze until you get a crash message.

Delete tool can only be used by selecting rectangles of objects to delete (just clicking on an object won't delete it).

How does one select an annotation object, by the way? Clickin on it doesn't work while the Lock View Tool is selected. Is it with the Move Tool?

**Comment by stefano-malacrino** [comment]
> In commit dd989e2, "Move Tool" with ~40,000 annotations, hangs up the interface. Just clicking on it, makes the interface freeze until you get a crash message.

Currently the tools that rely on paperjs hitTest function freeze with a high number of annotations. I'm planning to fix it next week.

> Delete tool can only be used by selecting rectangles of objects to delete (just clicking on an object won't delete it).

I believe this is the intended behaviour.

> How does one select an annotation object, by the way? Clickin on it doesn't work while the Lock View Tool is selected. Is it with the Move Tool?

Yes, items can be selected with the Move Tool. Once an item is selected it can be deleted hitting the Delete key.

**Comment by rcasero** [comment]
Just quick note that in new commit 95a02bf03289a8bd382647b1229f7d5052760e1d the problem persists.

**Comment by rcasero** [comment]
Works in commit 7b555aa8bf3360f82893e0a10582220207df5f5b
