### ISSUE TITLE
Select tool delete object when selecting another object

### ISSUE THREAD

**Issue by rcasero** [alanaberdeen/annotate#20]
Seen in commit 7b555aa8bf3360f82893e0a10582220207df5f5b

To reproduce the issue, open an image with annotations.

Click on an object, which selects it, and makes the filling transparent. Then click on another object. The first object gets deleted.

At least this happens when both object are overlapping with a third larger object that has the viewable switch off.

If after clicking on the first object you click on an area without any object in it, the first object gets deselected and not deleted, as expected.

**Comment by rcasero** [comment]
This bug is still present. Currently, for example, in a file with a large number of annotations, using the Delete tool to delete some closed contours, and then clicking on the "Lock View Tool" and moving the image, will delete a bunch of random annotations in the image.

Currently, the Delete tool is also the only feasible tool to delete annotations, as  clicking on the "Move Tool" to select an annotation in order to then delete with the Delete button will crash the GUI.

The Nodes tool allows to select an object without the GUI crashing, but the Delete or Backspace buttons don't delete the object.

**Comment by rcasero** [comment]
A workaround seems to be to use the Delete tool, and then directly clicking on the small navigation window.

**Comment by alanaberdeen** [comment]
Sorry, very late to these posts. Need to find an effective way of managing Github notifications. 

There were a lot of issues with the Move tool. It was a sloppy implementation that tried to do too many things at once. @stefano-malacrino implemented a cleaner more robust equivalent in the Reshape tool (first on the toolbar). I think this should alleviate some of the pain we were seeing with the older Move tool.
