### ISSUE TITLE
How to implement the function of annotating images

### ISSUE THREAD

**Issue by djshu** [alanaberdeen/annotate#3]
Hello, after look through nearly 20 image annotation tools, I find your tool is the best! Especially your tool can draw curve easily, that's to say, we can annotate images by sylus! I clone your code and follow your instructions in issue#1, type `npm run build`to build the project, then I run the commands below to check the project

`sudo npm install -g serve `
`serve -s dist`
but I got the pages

![2018-07-27 18-46-07](https://user-images.githubusercontent.com/25275145/43317935-7b248fb0-91d1-11e8-9fbd-20b2f2733516.png)

In fact, I want to get the project like your demo:

![2018-07-27 19-17-36](https://user-images.githubusercontent.com/25275145/43318028-d302b626-91d1-11e8-805e-3814658afaab.png)

So how can I get the project run as your demo and annotate my own images? Can you give me some help? Thank you very much!

**Comment by alanaberdeen** [comment]
Hi @djshu,

Glad to hear you like to the tool!

If I understand correctly you want to serve the editor interface by default? 
The page routes are defined in `src/router/index.js`, you'd be after the first entry in the list of routes. 
Change the component attribute for the path  `'/'` to `Editor`. See below: 

```
 {
    path: '/',
    name: 'Landing',
    component: Editor
  }  
```

Additionally, the editor instance can be pre-defined by a JSON. See some [documentation here](https://aida.gitbook.io/docs/). Point the interface to your JSON via setting the `endpoint` variable in the `loadProject()` function, `src/store/modules/common/index.js`.

This is a little clunky at the moment. I'd love to spend some time to make it easier for people to get going and it's definitely in the pipeline but just don't have the space just now. 

Let me know if you have any feedback

**Comment by djshu** [comment]
Wow, thank you! I got the demo I want. But how to open an image to annotate? I try to load an image like this, but nothing loaded. The feature I need is that I open a directory that contains many images, then I annotate images one by one, and save annotation for each image. Can you give me some tips to achieve it?
![2018-08-02 11-37-32](https://user-images.githubusercontent.com/25275145/43561471-c0b4c168-9649-11e8-8d13-e48a29570d22.png)

**Comment by anupamme** [comment]
Hello, I also have similar question where I want to upload a DICOM image however I am not able to upload any image. So my question is in addition to how to upload, is can we upload a DICOM image directly?

**Comment by alanaberdeen** [comment]
Hi all, 

Sorry to be slow on this. Haven't been on track of any Github notifications for a while and just came across these.

The online demo still needs a significant amount of work to fully function in the way you describe. If you are just annotating for yourself then it might be useful to run the application locally. This would enable you to easily include your own images. 

See the README for details on this. 

Again, sorry to be slow and miss these issues. Hope it helps!

**Comment by alanaberdeen** [comment]
@anupamme Specifically on the topic of DICOM. 

The application won't be able to load the DICOM images directly. I recommend using a combination of [openslide](https://openslide.org/) and [libvips](https://jcupitt.github.io/libvips/) to convert your DICOM images to Deep Zoom. This will enable openseadragon, the image library in AIDA, to read the image files.
