### ISSUE TITLE
Bug with `cp aidaLocal/* dist` in `package.json`

### ISSUE THREAD

**Issue by rcasero** [alanaberdeen/annotate#30]
Hi @alanaberdeen ,

I think there's a bug here

https://github.com/alanaberdeen/AIDA/blob/696ae7572f5a35a7da090322317ab27d73718fa7/package.json#L9

I think the line should be

```
    "build:darwin:linux": "vue-cli-service build && cp -r aidaLocal/* dist",
```

Without the `-r`, when you do 

```
npm run-script build
```

you get the error

```
cp: -r not specified; omitting directory 'aidaLocal/node_modules'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aida@0.1.0 build:darwin:linux: `vue-cli-service build && cp aidaLocal/* dist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aida@0.1.0 build:darwin:linux script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/rcasero/.npm/_logs/2020-07-22T23_41_57_261Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aida@0.1.0 build: `run-script-os`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the aida@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by stefano-malacrino** [comment]
Hi @rcasero ,

You shouldn't have the `node_modules` folder inside `aidaLocal`. You probably created it by executing by mistake `npm install` inside `aidaLocal`. If you delete the folder the build should complete successfully.

On a side note, in case you are interested in deploying AIDA without having to build it, you can checkout the `gh-pages` branch, which contains a build always up to date with the latest commit (@alanaberdeen the README probably should be updated to reflect this).

**Comment by alanaberdeen** [comment]
@stefano-malacrino definitely. I'll push a little update to the README.
