### ISSUE TITLE
How do i upload an image into the editor?

### ISSUE THREAD

**Issue by boazpetersil** [alanaberdeen/annotate#4]
EDIT: I saw that others had the same issue.
Is it possible to fix this issue with a "patch" by replacing the "Rembrandt" image with my supplied image? I don't mind hard coding this change every time i need to annotate a different image (currently the annotations are only for my purposes, no users involved)  

Thanks, and sorry for not reading other issues first
_______________________________________________________________________________________________________
Hi,
First of all wanted to sat the editor seems very nice!
But i can't seem to upload an image for annotation.. 

The steps i took:
1)typed "yarn serve"
2)entered localhost:8080
3)clicked the settings logo, selected "Add an Image"
4)under source iv'e tried entering the file path to my image and even a url to a google drive image, under name i entered "bla"
5)clicked the "submit"

but nothing happened :(

what am i doing wrong?

**Comment by alanaberdeen** [comment]
Hi, 

Sorry I completely missed this issue. Just stumbled across it now! 

The full functionality that you describe above isn't fully fleshed out in the online demo sorry about that. There's a lot of work to be done there. 

If you're annotating for yourself then it might be useful to run the application locally. I recently made a load of changes to make this easy. Essentially there is a local build included with the source and a nodeJS application to run a local server. You can then annotate your images on your machine simply by putting them in a specific sub-directory. See the README for details on this. 

Again, sorry to miss this. Hope this might be helpful late in the day!
