### ISSUE TITLE
Viewing Zeiss .czi files

### ISSUE THREAD

**Issue by rcasero** [alanaberdeen/annotate#41]
Hi,

We have some new Zeiss .czi histology files. It seems that libvips does not support .czi to convert it to DeepZoom. I've put a .czi file directly in an AIDA `images` directory to see whether that worked by any chance, but when I go to the AIDA web interface and ciock on the file, it just loads a white image, so I guess it doesn't work. Do you guys have a preferred way to deal with .czi files?

Kind regards,

Ramon.

**Comment by alanaberdeen** [comment]
Hi Ramon, 

Hmm yes, we generally use [openslide](https://openslide.org/) which is what libvips is using under the hood too. 

I suggest trying [bfconvert](https://docs.openmicroscopy.org/bio-formats/5.7.1/users/comlinetools/conversion.html) from the Bio-Formats team. I think that should play nicely with Zeiss formats. From there you could go to ome.tiff or DeepZoom. 

Best,
Alan

**Comment by rcasero** [comment]
OK, it turns out that the files we got from the scanner were corrupted, sorry. Thanks for the pointers, anyway.
