### ISSUE TITLE
Errors with "Run locally" and "Develop"

### ISSUE THREAD

**Issue by rcasero** [alanaberdeen/annotate#5]
Hi, following the instructions in ["Run locally"](https://github.com/alanaberdeen/AIDA/blob/master/README.md#run-locally) on Ubuntu 17.10. I get the error:

```bash
~/Software/AIDA/dist$ node aidaLocal.js
/home/rcasero/Software/AIDA/dist/aidaLocal.js:7
async function checkForImages () {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
```

And when trying the ["Develop"](https://github.com/alanaberdeen/AIDA/blob/master/README.md#develop) instructions, I get the error

```bash
~/Software/AIDA/dist$ npm run serve
npm ERR! Linux 4.13.0-46-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "serve"
npm ERR! node v6.11.4
npm ERR! npm  v3.5.2

npm ERR! missing script: serve
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rcasero/Software/AIDA/dist/npm-debug.log
```

**Comment by alanaberdeen** [comment]
Hi @rcasero, 

I'm pretty sure this is down to using an old version of nodeJS. 

The error message you posted above indicates you were running v6.11.4 and I can replicate the first error you received for running locally. I also get similar issues when trying the development builds. 

Try grabbing the [latest versions here](https://nodejs.org/en/), if there are still problems I'll dig a bit deeper!

**Comment by rcasero** [comment]
Thanks, @alanaberdeen .

I've [installed the latest (stable) version of node.js in Ubuntu](https://linuxize.com/post/how-to-install-node-js-on-ubuntu-18.04/) with

```bash
curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
sudo apt-get install -y nodejs
```

This currently installs 

```bash
$ node --version
v10.6.0
```

Now it runs correctly

```bash
~/Software/AIDA/dist$ node aidaLocal.js


Running AIDA at http://localhost:3000/
```
