### ISSUE TITLE
How to add images to starting menu?

### ISSUE THREAD

**Issue by rcasero** [alanaberdeen/annotate#6]
Hi @alanaberdeen ,

Not sure whether this is related to issue #4 .

I'm [running AIDA locally](https://github.com/alanaberdeen/AIDA/blob/master/README.md#run-locally), on `http://localhost:3000/`, as per AIDA instructions.

In the starting page, I can see there's one image available, `example.jpg`. This image lives in `~/Software/AIDA/dist/data/images`. As a test, I've copied this image with another name, `foo.jpg` in the same directory.

The initial menu doesn't see `foo.jpg` yet, after refreshing the AIDA starting page.

I assume the list of files is in `~/Software/AIDA/dist/data/images.json`, which contains

```
["example.jpg"]
```

I've tried editing this file with different variations, and reloading the AIDA page, but none of these seem to expand the menu with the new `foo.jpg` file

```
["example.jpg", "foo.jpg"]
```

```
["example.jpg"; "foo.jpg"]
```

```
["example.jpg"]
["foo.jpg"]
```

How do I do this? On a related note, my files are `.ndpi`. Should I copy the `.ndpi` file to the `images` directory, or should I first convert to `.dzi` and then copy the resulting DeepZoom files?

**Comment by rcasero** [comment]
Answer to first question is that no file editing is needed. 

When the server starts, it [reads the image directory for new images](https://github.com/alanaberdeen/AIDA/blob/59c28ee3c3e7a86ab3e7fe08d11850e3ab191387/dist/aidaLocal.js#L70), and automatically updates `~/Software/AIDA/dist/data/images.json` when new images are added to `~/Software/AIDA/dist/data/images/` and the page is reloaded, e.g. as

```
["example.jpg","foo.jpg"]
```

**Comment by rcasero** [comment]
Answer to second question is that `.ndpi` files cannot be read by AIDA.

You need to install `libvips` with

```bash
sudo apt install libvips
```

and then convert the file with e.g.

```bash
vips VipsForeignSaveDz file.ndpi ~/Software/AIDA/dist/data/images/file
```

This will create a '.dzi' file and the corresponding directory of image tiles

```
KLF14-B6NTAC-MAT-18.2b  58-16 B3 - 2016-02-03 11.01.43.dzi
KLF14-B6NTAC-MAT-18.2b  58-16 B3 - 2016-02-03 11.01.43_files
```

**Comment by alanaberdeen** [comment]
Hi @rcasero, 

Glad this all worked out. You are exactly right in your findings. 
I'll try to write up some more thorough docs asap that will reference all these little things!

**Comment by alanaberdeen** [comment]
@rcasero 
[Started throwing together a wiki](https://github.com/alanaberdeen/AIDA/wiki). Feel free to contribute to anything you find that needs a little more explanation!

**Comment by rcasero** [comment]
@alanaberdeen That's a great idea, I will

**Comment by BalachandraTejas** [comment]
Sorry for commenting on a closed issue, but my issue is closely related.
While I run in Development mode, no images are listed. Showing "No data available"
Please tell where I should put the images for running in development mode.

**Comment by alanaberdeen** [comment]
Hey @BalachandraTejas, no problem. 

The steps are essentially the same as those [laid out here in the ReadMe](https://github.com/alanaberdeen/AIDA#run-locally)

1. Clone the repository 
2. `cd` to `/dist`
3. Install dependencies via `npm install`
4. Add the images you want to annotate to the `/dist/data/images` directory. 
5. Run the nodeJS local application via `node aidaLocal.js`

Now if you want to run an additional hot-reloading development server... 

6. `cd` to `AIDA`
7. Install dependencies via `npm install`
8. start a hot-reloading dev server with `npm run serve`

This should leave you with a development build running at `http://localhost:8080/` and referencing an expressJS backend running at `http://localhost:3000/`
